name: Build Deno app

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: 📂 SFTP uploader                       # Upload to SFTP 
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: 89.223.67.30
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          compress: false
          forceUpload: true
          localDir: './'
          remoteDir: '/var/www/vtp/'
          exclude: '.git*,.DS_Store' 

      # - name: SSH Push
      #   uses: ErenKrt/ssh-push@1.3
      #   with:
      #     host: 89.223.67.30
      #     username: root
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     source: "./"
      #     destination: "/var/www/vtp/repo.tar.gz"
          # scripts: |
          #   cd /var/www/vtp && tar -xvf repo.tar.gz
          #   rm -rf /var/www/repo.zip
