name: Build Deno app

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: Build binary file
        run: deno task build

      - name: List of files
        run: ls -lh

      # - name: SSH Push
      #   uses: ErenKrt/ssh-push@1.3
      #   with:
      #     host: 89.223.67.30
      #     username: root
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     source: "./"
      #     destination: "/var/www/vtp/app.zip"
      #     scripts: |
      #       cd /var/www/vtp && unzip app.zip
      #       rm -rf /var/www/vtp/app.zip
      #       cd /var/www/vtp && deno task build
