name: Build Deno app

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  Lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - name: ls -lh
        run: ls -lh
  
  BuildAndDeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: SSH Push
        uses: ErenKrt/ssh-push@1.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "./"
          destination: "/var/www/vtp/app.zip"
          scripts: |
            cd /var/www/vtp && unzip app.zip
            rm -rf /var/www/vtp/app.zip
            cd /var/www/vtp && deno task build
